algoritmo "semnome"
// Função : Elabore um algoritmo que receba o nome de um usuário e envie
// uma mensagem de saudação
// Autor :
// Data : 12/03/2025
// Seção de Declarações 
var
nome: caracter
inicio
// Seção de Comandos
//Entrada de dados:
escreval ("Favor digitar seu nome: ")
leia(nome)
//Saída de dados:
escreva("Olá ")
escreva(nome)
escreva(", seja bem vindo")
fimalgoritmo
