algoritmo "semnome"
// Função :
// Autor :
// Data : 12/03/2025
// Seção de Declarações 
var
num1: inteiro
num2: inteiro
soma: inteiro
inicio
// Seção de Comandos
// Entrada de Dados
escreva("Digite o primeiro número inteiro: ")
leia(num1)
escreva("Digite o primeiro número inteiro: ")
leia(num2)

//processamento de dados:
soma <- num1 + num2

//Saída de dados
escreval ("O resultado da soma de: ", num1, " com ", num2, " é: ", soma)
fimalgoritmo
